"""make_resume_id_nullable

Revision ID: 3bc8e1d312a9
Revises: d5aef4bbf0f1
Create Date: 2025-11-01 19:30:58.885295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc8e1d312a9'
down_revision: Union[str, None] = 'd5aef4bbf0f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_analyses', 'resume_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_analyses', 'resume_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
